# Generated by Django 5.2.6 on 2025-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('brand', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.CharField(max_length=4)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(default=0, help_text='Ціна у гривнях')),
            ],
        ),
    ]
